In [1]:
l = [23245, 27, 546, 215, -1234]
l

[23245, 27, 546, 215, -1234]

In [2]:
import numpy as np

In [3]:
np.array(l)

array([23245,    27,   546,   215, -1234])

In [4]:
a = np.array(l)
print(a)

[23245    27   546   215 -1234]


In [5]:
b = np.array([12, 435, 63.3,True, "abc"])
print(b)

['12' '435' '63.3' 'True' 'abc']


In [6]:
l.pop()

-1234

In [7]:
l

[23245, 27, 546, 215]

In [8]:
a.min()

-1234

In [9]:
a.mean()

4559.8

In [10]:
a

array([23245,    27,   546,   215, -1234])

In [11]:
c = np.array([12, 435, 63.3,True])

In [12]:
print(c)

[ 12.  435.   63.3   1. ]


In [13]:
type(c)

numpy.ndarray

In [14]:
c.mean()

127.825

In [15]:
a

array([23245,    27,   546,   215, -1234])

In [16]:
#slicing arrays and a function
a[:2].mean()

11636.0

In [17]:
len(a)

5

In [18]:
l

[23245, 27, 546, 215]

In [44]:
a = np.array(l)
a

array([23245,    27,   546,   215])

In [45]:
a[:]

array([23245,    27,   546,   215])

In [46]:
a[::2]

array([23245,   546])

In [48]:
b = a[::2]
b

array([23245,   546])

In [51]:
b[:] = 312
b

array([312, 312])

In [52]:
print(a)

[312  27 312 215]
