In [3]:
import numpy as np
j = np.array([23245,    27,   546,   215, -1234])
j

array([23245,    27,   546,   215, -1234])

In [4]:
 j[2:]

array([  546,   215, -1234])

In [6]:
j[2:4]

array([546, 215])

In [8]:
b = j[2:4] #array do not create a copy of the array but a view unlike in list

In [9]:
b

array([546, 215])

In [10]:
b[0]

546

In [12]:
b[:] = 111

In [14]:
j

array([23245,    27,   111,   111, -1234])

In [17]:
x = j.copy()
x

array([23245,    27,   111,   111, -1234])

In [19]:
j

array([23245,    27,   111,   111, -1234])

In [20]:
import array as arr
from numpy import array as arr